### ISSUE TITLE
Fetch returns 404

### ISSUE THREAD

**Issue by jefsev** [markmead/hyperjs#18]
He @markmead 

I get a 404 in the preview: https://www.hyperjs.dev/examples/accordion-a11y

Forked your repo to check it locally but when i run the site on localhost:3000 using npm run dev and watch it works fine. Maybe something with the npm run build on the server when deploying? 

Just wanted to let you know, if i can do anything just point me in the right direction.

**Comment by markmead** [comment]
Oof that's come out of no where 😅

It's fixed now but no idea what has caused that, thanks for letting me know!

**Comment by jefsev** [comment]
Np :P
