### ISSUE TITLE
[BUG] Lowercase Issue

### ISSUE THREAD

**Issue by pavelloz** [markmead/hyperjs#26]
Hello,

I found a small bug :)

https://www.hyperjs.dev/components/input-lowercase

^ set your cursor between the words, press shift (or caps lock) and start typing.
After first letter, cursor will jump to the end of string and continue there.

Example:
<img width="261" alt="image" src="https://user-images.githubusercontent.com/546845/184494678-a27c47ce-9ef3-4992-b092-4f57266aabcc.png">

**Comment by markmead** [comment]
Thanks for the report @pavelloz PRs are welcome if you wanted to take a crack at it.
