### ISSUE TITLE
Negative Zero in Input positive number with alpinejs

### ISSUE THREAD

**Issue by nickpreston24** [markmead/hyperjs#55]
![image](https://github.com/markmead/hyperjs/assets/9275026/0f2c9ace-7093-4657-8698-8da14adeb8e0)

To reproduce:
1. Navigate [here](https://js.hyperui.dev/examples/form-input-positive-number) to the example.
2. Type `0` in the box, then change the cursor to be before the 0, and tap the hyphen `-`.

You'll get `-0` or `--0`.

Hope this helps.

**Comment by markmead** [comment]
0 isn't negative or positive.
