### ISSUE TITLE
Slideshow and slider components

### ISSUE THREAD

**Issue by Samanw** [markmead/hyperjs#56]
would be great if there be a slideshow with nav dot and arrows
and slider which shows number of set items for example https://getuikit.com/docs/slider

**Comment by markmead** [comment]
Hi @Samanw,

It's a good idea , thank you! Only thing holding me back is which library to use? Usually reaching for `keen-slider` more recently but there are so many options out there.

**Comment by markmead** [comment]
Nope, it would have to use a package. I'm not building a slider with Alpine JS! 😅
