### ISSUE TITLE
Docs are down

### ISSUE THREAD

**Issue by enesyueksek** [markmead/hyperjs#58]
Hey there, just wanted to let you know that your docs are down currently.

When clicking on the sub-page it shows a 500 internal server msg :)

**Comment by markmead** [comment]
I assume you mean for js.hyperui.dev, right? I have downgraded the version of Next JS which should be the fix. However, there are still errors in the console. I'll keep looking.

**Comment by markmead** [comment]
Should be all resolved now from #59
